repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: bash -c 'uv run ruff check --config=pyproject.toml --fix'
        language: system
        types_or: [python, pyi]
        pass_filenames: true
        require_serial: false

      - id: ruff-format
        name: ruff format
        entry: bash -c 'uv run ruff format --config=pyproject.toml'
        language: system
        types_or: [python, pyi]
        pass_filenames: true
        require_serial: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--config-file, "./pyproject.toml"]
        files: ^src/
        additional_dependencies:
          - sqlalchemy[mypy]
          - pydantic[email]
          - pydantic-settings
          - alembic
          - asyncpg
          - httpx
          - pytest
          - sentry-sdk
          - "aiogram>=3.24.0"
          - "beautifulsoup4"
          - "playwright"
