name: job-tracker

services:
  rabbitmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: rabbitmq_v4.2
    hostname: "rabbitmq"
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT_STREAM_PROTOCOL?Variable not set}:5552" # RabbitMQ Stream Protocol
      - "${RABBITMQ_PORT_AMQP?Variable not set}:5672" # AMQP
      - "${RABBITMQ_PORT_MANAGEMENT_UI?Variable not set}:15672" # Management UI
      - "${RABBITMQ_PORT_PROMETHEUS?Variable not set}:15692" # Prometheus Metrics
    environment:
      - TZ=Europe/Moscow
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER?Variable not set}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS?Variable not set}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./data/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
volumes:
  rabbitmq_data:

networks:
  app-network:
