name: job-tracker

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  rabbitmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: rabbitmq_v4.2
    hostname: "rabbitmq"
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT_STREAM_PROTOCOL?Variable not set}:5552" # RabbitMQ Stream Protocol
      - "${RABBITMQ_PORT_AMQP?Variable not set}:5672" # AMQP
      - "${RABBITMQ_PORT_MANAGEMENT_UI?Variable not set}:15672" # Management UI
      - "${RABBITMQ_PORT_PROMETHEUS?Variable not set}:15692" # Prometheus Metrics
    environment:
      - TZ=UTC
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER?Variable not set}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS?Variable not set}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./data/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - app-network
    <<: *default-logging

  scrapper:
    image: job-tracker:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - job-tracker:latest
        - job-tracker:${TAG:-latest}
    container_name: scrapper_${TAG:-latest}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "glitchtip.local:host-gateway"
      - "lm-studio.local:host-gateway"
    restart: unless-stopped
    command: ["run_scrapper"]
    environment:
      - ENVIRONMENT=${ENVIRONMENT?Variable not set}
      - RABBITMQ__URL=${RABBITMQ__URL?Variable not set}
      - AI_ANALYST__BASE_URL=${AI_ANALYST__BASE_URL?Variable not set}
      - AI_ANALYST__API_KEY=${AI_ANALYST__API_KEY?Variable not set}
      - AI_ANALYST__MODEL=${AI_ANALYST__MODEL?Variable not set}
      - RUN_MIGRATIONS=true
    volumes:
      - ./data:/app/data
      - ./settings.toml:/app/settings.toml:ro
    networks:
      - app-network
    depends_on:
      - rabbitmq
    <<: *default-logging

  tg_bot:
    image: job-tracker:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - job-tracker:latest
        - job-tracker:${TAG:-latest}
    container_name: tg_bot_${TAG:-latest}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "glitchtip.local:host-gateway"
    restart: unless-stopped
    command: ["run_bot"]
    environment:
      - RABBITMQ__URL=${RABBITMQ__URL?Variable not set}
      - TG_BOT__ENVIRONMENT=${ENVIRONMENT?Variable not set}
      - TG_BOT__TOKEN=${TG_BOT__TOKEN?Variable not set}
      - TG_BOT__USER_IDS=${TG_BOT__USER_IDS?Variable not set}
    volumes:
      - ./data:/app/data
      - ./settings.toml:/app/settings.toml:ro
    networks:
      - app-network
    depends_on:
      - rabbitmq
      - scrapper
    <<: *default-logging

volumes:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
