"""Added vacancy table.

Revision ID: 38045ae32b61
Revises:
Create Date: 2026-02-13 05:37:51.719861

"""

from collections.abc import Sequence  # noqa: TC003

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38045ae32b61"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancys",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancys")),
    )
    op.create_index(
        op.f("ix_vacancys_hash"), "vacancys", ["hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacancys_hash"), table_name="vacancys")
    op.drop_table("vacancys")
    # ### end Alembic commands ###
